# 07_table_creation.R
# ============================================================================
# PURPOSE: Create publication-quality tables for the manuscript (Tables 1 & 2)
#
# Table 1 (Univariate): Ranks 16 single-predictor models by their improvement
#   over the intercept-only baseline (ΔR², ΔRMSE, ΔAIC). Averaged across
#   growing season days and all 7 land cover types.
#   Source: univariate_table.csv (generated by script 04)
#
# Table 2 (Multivariate Additive): Ranks additive drought+temperature models
#   by the same metrics. Shows which drought × temperature combination works best.
#   Source: multivarAdditive_table.csv (generated by script 05)
#
# Both tables are saved as Word documents (.docx) using flextable/officer.
#
# SIGNIFICANT FIGURES:
#   ΔAIC:  1 decimal place (values ~13-17, range of ~4)
#   ΔR²:   3 decimal places (values ~0.15-0.17, range of ~0.02)
#   ΔRMSE: 4 decimal places (values ~-0.010, range of ~0.001)
#   At 3dp, all 16 models show ΔRMSE = -0.010 — 4dp is required to distinguish.
# ============================================================================

library(ggplot2)
library(lubridate)
library(ggcorrplot)
library(flextable)
library(officer)
library(dplyr)

# Setting the file paths. This may be different for your computer.
# Google Drive path: Urban Ecological Drought / Manuscript - Urban Drought NDVI Daily Corrs
Sys.setenv(GOOGLE_DRIVE = "G:/Shared drives/Urban Ecological Drought/Manuscript - Urban Drought NDVI Daily Corrs/")
# Sys.setenv(GOOGLE_DRIVE = "~/Google Drive/Shared drives/Urban Ecological Drought/Manuscript - Urban Drought NDVI/")
google.drive <- Sys.getenv("GOOGLE_DRIVE")

# Data path: reads from Google Drive if available, otherwise falls back to local processed_data/
if (dir.exists(file.path(google.drive, "data/processed_files"))) {
  pathData <- file.path(google.drive, "data/processed_files")
  cat("Reading data from Google Drive:", pathData, "\n")
} else {
  pathData <- "processed_data"
  cat("Google Drive not found, reading from local processed_data/\n")
}

pathSave <- file.path(google.drive, "pub_figs")


# =============================================================================
# VARIABLE RECODING LOOKUP TABLES
# =============================================================================
# Map internal model/variable codes (from the R analysis pipeline) to
# human-readable names for publication. The internal names reflect the column
# names in the original GRIDMET data files (e.g., "X30d.SPEI" → "SPEI 30-day").

# Univariate model name mappings (16 climate variables tested in script 03)
univariate_model_mapping <- c(
  # Drought indices
  "SPEI14" = "SPEI 14-day",
  "SPEI30" = "SPEI 30-day", 
  "SPEI60" = "SPEI 60-day",
  "SPEI90" = "SPEI 90-day",
  "SPI14day" = "SPI 14-day",
  "SPI30day" = "SPI 30-day",
  "SPI60day" = "SPI 60-day", 
  "SPI90day" = "SPI 90-day",
  
  # Temperature indices
  "Tmax_14day" = "Tmax 14-day",
  "Tmax_30day" = "Tmax 30-day",
  "Tmax_60day" = "Tmax 60-day", 
  "Tmax_90day" = "Tmax 90-day",
  "Tmin_14day" = "Tmin 14-day",
  "Tmin_30day" = "Tmin 30-day",
  "Tmin_60day" = "Tmin 60-day",
  "Tmin_90day" = "Tmin 90-day"
)

# Drought variable mappings for multivariate table
drought_variable_mapping <- c(
  "SPEI14" = "SPEI 14-day",
  "SPEI30" = "SPEI 30-day",
  "SPI30day" = "SPI 30-day",
  "SPI60day" = "SPI 60-day"
)

# Temperature variable mappings for multivariate table  
temperature_variable_mapping <- c(
  "Tmax_30day" = "Tmax 30-day",
  "Tmax_14day" = "Tmax 14-day", 
  "Tmin_60day" = "Tmin 60-day",
  "Tmax_60day" = "Tmax 60-day"
)

# =============================================================================
# FUNCTION TO APPLY RECODING
# =============================================================================

recode_variables <- function(data, column_name, mapping_table) {
  # Recode variables using a lookup table
  # 
  # Args:
  #   data: dataframe containing the column to recode
  #   column_name: name of column to recode  
  #   mapping_table: named vector with old_name = new_name mappings
  #   
  # Returns:
  #   dataframe with recoded column
  
  # Store original values
  original_values <- data[[column_name]]
  
  # Check if all values in the column have mappings
  unmapped_values <- setdiff(unique(original_values), names(mapping_table))
  if (length(unmapped_values) > 0) {
    warning(paste("Unmapped values found:", paste(unmapped_values, collapse = ", ")))
  }
  
  # Apply the mapping
  data[[column_name]] <- mapping_table[original_values]
  
  # For any unmapped values (resulting in NA), keep the original value
  na_indices <- is.na(data[[column_name]])
  data[[column_name]][na_indices] <- original_values[na_indices]
  
  return(data)
}

# =============================================================================
# TABLE 1: UNIVARIATE MODEL COMPARISON
# =============================================================================
# Input: univariate_table.csv — 16 rows (one per met variable), pre-ranked.
# Created by script 04 from growing-season-only (DOY 91-304) means.
# Delta metrics are relative to the intercept-only model:
#   ΔR²:   positive = explained more variance than intercept-only
#   ΔRMSE: negative = lower prediction error than intercept-only
#   ΔAIC:  negative = better fit than intercept-only (but all are positive here
#          because adding a predictor to a mixed model can increase AIC if the
#          improvement doesn't offset the complexity penalty)

cat("Processing univariate table...\n")

# Load univariate data
univar.tab <- read.csv(file.path(pathData, "univariate_table.csv"), header = T)

# Apply model name recoding using correct column name "model" (lowercase)
univar.tab <- recode_variables(univar.tab, "model", univariate_model_mapping)

# Round decimals — use 4 decimal places for ΔRMSE (values ~0.01, 3dp makes all
# models indistinguishable at -0.010). dAIC to 1dp, dR2 to 3dp.
univar.tab$dAIC  <- round(univar.tab$dAIC, digits = 1)
univar.tab$dR2   <- round(univar.tab$dR2, digits = 3)
univar.tab$dRMSE <- round(univar.tab$dRMSE, digits = 4)

# Update column names with proper formatting
colnames(univar.tab) <- c("Model", "ΔAIC", "ΔR²", "ΔRMSE", "ΔRMSE (%)",
                          "R² Rank", "RMSE Rank", "Avg. Rank", "Combined Rank")

# Drop unnecessary columns
univar.tab <- univar.tab[, !names(univar.tab) %in% c("Avg. Rank", "ΔRMSE (%)")]

# Create publication-quality flextable
ft_univar <- flextable(univar.tab) |>
  colformat_num(j = "ΔAIC", digits = 1) |>
  colformat_num(j = "ΔR²", digits = 3) |>
  colformat_num(j = "ΔRMSE", digits = 4) |>
  width(j = 1, width = 1.5) |>
  width(j = 2:4, width = 1.1) |>
  width(j = 5:7, width = 0.8) |>
  theme_booktabs() |>
  # Add better formatting
  bold(part = "header") |>
  align(align = "center", part = "header") |>
  align(j = 1, align = "left", part = "body") |>
  align(j = 2:7, align = "center", part = "body")

# Save univariate table
doc_univar <- read_docx() |>
  body_add_par("Table 1. Univariate Model Comparison", style = "heading 1") |>
  body_add_flextable(ft_univar)

print(doc_univar, target = file.path(google.drive, "pub_figs", "univar_model_comparison_table.docx"))
cat("Univariate table saved successfully.\n")

# =============================================================================
# TABLE 2: MULTIVARIATE ADDITIVE MODEL COMPARISON
# =============================================================================
# Input: multivarAdditive_table.csv — additive models only (interactions filtered
# out). Each row is a drought+temperature variable combination, ranked by the
# same delta metrics as Table 1 but now relative to the lag-only baseline.
# Created by script 05 from growing-season-only (DOY 91-304) means.
#
# The "Model" and "Model Type" columns are dropped since all rows are additive
# and the drought/temperature variables are shown separately.

cat("Processing multivariate table...\n")

# Load multivariate data
multivar.tab <- read.csv(file.path(pathData, "multivarAdditive_table.csv"), header = T)

# Apply variable recoding using the actual column names from your data
multivar.tab <- recode_variables(multivar.tab, "DroughtVar", drought_variable_mapping)
multivar.tab <- recode_variables(multivar.tab, "TempVar", temperature_variable_mapping)

# Update column names with proper formatting (using actual column structure)
colnames(multivar.tab) <- c("Model", "Drought Variable", "Temperature Variable", "Model Type", 
                            "ΔAIC", "ΔR²", "ΔRMSE", "AIC Rank", "R² Rank", "RMSE Rank", 
                            "Avg. Rank", "Combined Rank")

# Drop unnecessary columns  
multivar.tab <- multivar.tab[, !names(multivar.tab) %in% c("Model", "Model Type", "Avg. Rank")]

# Round decimals — match univariate table sig figs
multivar.tab[, "ΔAIC"] <- round(multivar.tab[, "ΔAIC"], digits = 1)
multivar.tab[, "ΔR²"]  <- round(multivar.tab[, "ΔR²"], digits = 3)
multivar.tab[, "ΔRMSE"] <- round(multivar.tab[, "ΔRMSE"], digits = 4)

# Create publication-quality flextable
ft_multivar <- flextable(multivar.tab) |>
  colformat_num(j = "ΔAIC", digits = 1) |>
  colformat_num(j = "ΔR²", digits = 3) |>
  colformat_num(j = "ΔRMSE", digits = 4) |>
  width(j = 1:2, width = 1.5) |>
  width(j = 3:5, width = 1.1) |>
  width(j = 6:8, width = 0.8) |>
  theme_booktabs() |>
  # Add better formatting
  bold(part = "header") |>
  align(align = "center", part = "header") |>
  align(j = 1:2, align = "left", part = "body") |>
  align(j = 3:8, align = "center", part = "body")

# Save multivariate table
doc_multivar <- read_docx() |>
  body_add_par("Table 2. Multivariate Model Comparison", style = "heading 1") |>
  body_add_flextable(ft_multivar)

print(doc_multivar, target = file.path(google.drive, "pub_figs", "multivar_model_comparison_table.docx"))
cat("Multivariate table saved successfully.\n")

# =============================================================================
# VALIDATION AND SUMMARY
# =============================================================================
# Print all variable recodings to console for verification. Confirms that
# internal codes were correctly mapped to publication-friendly names.

cat("\n=== RECODING SUMMARY ===\n")
cat("Univariate models recoded:\n")
for (i in seq_along(univariate_model_mapping)) {
  cat(paste0("  ", names(univariate_model_mapping)[i], " → ", univariate_model_mapping[i], "\n"))
}

cat("\nDrought variables recoded:\n")
for (i in seq_along(drought_variable_mapping)) {
  cat(paste0("  ", names(drought_variable_mapping)[i], " → ", drought_variable_mapping[i], "\n"))
}

cat("\nTemperature variables recoded:\n")
for (i in seq_along(temperature_variable_mapping)) {
  cat(paste0("  ", names(temperature_variable_mapping)[i], " → ", temperature_variable_mapping[i], "\n"))
}

cat("\nBoth tables have been saved with publication-ready formatting!\n")